(in-package :openldk)

(defclass <context> ()
  ((class :initarg :class)
   (is-clinit-p :initarg :is-clinit-p :initform nil)
   (uses-stack-p :initform nil)
   (blocks :initform nil)
   (block-end :initform nil)
   (locals :initform (list))
   (classes :initarg :classes :initform nil)
   (pc :initform 0)
   (stack :initform (cl-containers:make-container 'cl-containers:stack-container))
   (fn-name)
   (bytecode :initarg :bytecode)
   (ssa-code :initform nil)
   (exception-table :initarg :exception-table :initform nil)))

(defmethod flag-stack-usage ((context <context>))
  (setf (slot-value context 'uses-stack-p) t))
