compile and execute: TestIO
compile and execute: TestArithmetic
compile and execute: TestArrayAccess
compile and execute: TestClassInitializer
compile and execute: TestCompare
compile and execute: TestConstants
compile and execute: TestConversions
compile and execute: TestFieldAccess
compile and execute: TestFinally
compile and execute: TestInstanceOf
compile and execute: TestInterfaceCall
compile and execute: TestReturn
