on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main, windows ]
  pull_request:
    branches: [ main, windows ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install SBCL
        run: |
          curl -L -O "https://downloads.sourceforge.net/project/sbcl/sbcl/2.4.2/sbcl-2.4.2-x86-64-linux-binary.tar.bz2"
          tar -xf sbcl-2.4.2-x86-64-linux-binary.tar.bz2
          cd sbcl-2.4.2-x86-64-linux
          ./install.sh --prefix=$HOME/.local
          cd ..
          rm -rf sbcl-2.4.2-x86-64-linux-binary.tar.bz2 sbcl-2.4.2-x86-64-linux
        shell: bash
      - name: Install ocicl
        run: |
          curl -L https://github.com/ocicl/ocicl/archive/refs/tags/v1.0.19.tar.gz | tar xvfz -
          cd ocicl-1.0.19
          make && make install
          ~/.local/bin/ocicl setup > ~/.sbclrc
          echo "(pushnew (uiop:getcwd) asdf:*central-registry*)" >> ~/.sbclrc
          cd ..
          rm -rf ocicl-1.0.19
        shell: bash
      - name: Install rlgl
        run: |
          wget -qO - https://rl.gl/cli/rlgl-linux-amd64.tgz | tar --strip-components=2 -xvzf - ./rlgl/rlgl;
        shell: bash
      - name: Install dejagnu and java
        run: |
          sudo apt-get update
          sudo apt-get install dejagnu openjdk-8-jre
        shell: bash
      - name: Build and Test
        run: |
          ocicl install
          make
          LDK_CLASSPATH=/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/rt.jar make check RUNTESTFLAGS=aaa/run.exp
          RLGL_KEY=0LIBFFI-0LIBFFI-0LIBFFI-0LIBFFI
          ./rlgl l --key=${RLGL_KEY} https://rl.gl
          ./rlgl e -l project=openldk -l sha=${GITHUB_SHA:0:7} --policy=https://github.com/libffi/rlgl-policy.git */testsuite/openldk.log
        shell: bash
